when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    branch: ${CI_REPO_DEFAULT_BRANCH}

depends_on:
  - test
  - test-e2e

labels:
  platform: linux/amd64
  memory: 'high'

steps:
  build:
    image: docker.io/node:20-alpine
    commands:
      - apk add --no-cache zip git
      - yarn --frozen-lockfile
      - yarn build
      - if [ "${CI_PIPELINE_EVENT}" = "push" ] || [ "${CI_PIPELINE_EVENT}" = "manual" ]; then zip -9qr ${CI_REPO_DEFAULT_BRANCH}.zip dist/; fi

  upload-artifacts:
    image: docker.io/woodpeckercommunity/plugin-gitea-package:0.5.0
    settings:
      user:
        from_secret: pleroma-ci-user
      password:
        from_secret: pleroma-ci-password
      update: true
      owner: 'pleroma'
      package_name: 'pleroma-fe-builds'
      package_version: ${CI_REPO_DEFAULT_BRANCH}
      file_source: ./${CI_REPO_DEFAULT_BRANCH}.zip
      file_name: latest.zip
