when:
  - event: pull_request
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    branch: ${CI_REPO_DEFAULT_BRANCH}

steps:
  install-depends:
    image: &node-image
      docker.io/node:18-alpine
    commands:
      - yarn

  eslint:
    image: *node-image
    depends_on: install-depends
    commands:
      - yarn ci-eslint

  biome:
    image: *node-image
    depends_on: install-depends
    commands:
      - yarn ci-biome

  stylelint:
    image: *node-image
    depends_on: install-depends
    commands:
      - yarn ci-stylelint
