when:
  - event: pull_request
    evaluate: 'CI_COMMIT_SOURCE_BRANCH != "weblate" && not(CI_COMMIT_SOURCE_BRANCH startsWith "renovate/")'
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    branch: ${CI_REPO_DEFAULT_BRANCH}

labels:
  platform: linux/amd64
  memory: 'high'

variables:
  artifacts_uploader_settings: &artifacts_uploader_settings
    user:
      from_secret: pleroma-ci-user
    password:
      from_secret: pleroma-ci-password
    owner: 'pleroma'
    package_name: 'pleroma-fe-test-artifacts'
  script_file_entrypoint: &script_file_entrypoint
    - /bin/sh
    - -c
    - 'printf "%s" "$CI_SCRIPT" | base64 -d > /tmp/ci-script.sh && /bin/sh -xe /tmp/ci-script.sh'

steps:
  test:
    image: mcr.microsoft.com/playwright:v1.61.0-jammy
    environment:
      APT_CACHE_DIR: apt-cache
      DEBIAN_FRONTEND: noninteractive
      FF_NETWORK_PER_BUILD: "true"
      PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    entrypoint: *script_file_entrypoint
    commands:
      - |
        if [ "${CI_PIPELINE_EVENT}" != "pull_request" ]; then
          mkdir -pv $APT_CACHE_DIR && apt-get -qq update
          apt-get -y install zip
        fi
      - yarn --frozen-lockfile
      - |
        if ! yarn unit-ci; then
          [ "${CI_PIPELINE_EVENT}" = "pull_request" ] || zip -9qr ${CI_COMMIT_SHA:0:8}-screenshots.zip $(find . -type d -name __screenshots__)
          exit 1
        fi

  code-analysis:
    image: ghcr.io/j04n-f/sonar-plugin
    settings:
      sonar_token:
        from_secret: sonarqube-token
      sonar_url: https://sonarqube.pleroma.dev
      sonar_project_key: Pleroma-FE
      sonar_project_name: "Pleroma FE"

  upload-artifacts:
    image: docker.io/woodpeckercommunity/plugin-gitea-package:0.5.0
    when:
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
        status: [failure]
      - event: manual
        branch: ${CI_REPO_DEFAULT_BRANCH}
        status: [failure]
    settings:
      <<: *artifacts_uploader_settings
      package_version: ${CI_REPO_DEFAULT_BRANCH}-${CI_COMMIT_SHA:0:8}
      file_source: ./${CI_COMMIT_SHA:0:8}-screenshots.zip
      file_name: ${CI_COMMIT_SHA:0:8}-screenshots.zip
